approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmRegistryServer: "https://repo.huaweicloud.com/repository/npm/"
npmPublishRegistry: "https://registry.npmjs.org"


httpTimeout: 60000
httpRetry: 3